language: ruby
rvm:
  - "2.0.0"
before_install:
  - wget http://phantomjs.googlecode.com/files/phantomjs-1.9.1-linux-x86_64.tar.bz2
  - tar -xf phantomjs-1.9.1-linux-x86_64.tar.bz2
  - sudo rm -rf /usr/local/phantomjs
  - sudo mv phantomjs-1.9.1-linux-x86_64 /usr/local/phantomjs
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "bundle exec rspec spec && bundle exec guard-jasmine --server-timeout=120"
