language: ruby
rvm:
  - "2.0.0"
# uncomment this line if your project needs to run something other than `rake`:
script: "bundle exec rspec spec && export DISPLAY=:99.0 && bundle exec guard-jasmine --server-timeout=60"
